---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - cert.pem
      - private.key

  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=awx-postgres-15
      - port=5432
      - database=awx
      - username=awx
      - password=password
      - type=managed

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=password

  # If you want to specify SECRET_KEY for your AWX manually, uncomment following lines and change the value.
  # Refer AAC documentation for detail about SECRET_KEY.
  # https://docs.ansible.com/automation-controller/latest/html/administration/secret_handling.html
  #- name: awx-secret-key
  #  type: Opaque
  #  literals:
  #    - secret_key=MySuperSecureSecretKey123!

configMapGenerator:
  - name: logo-login-configmap
    files:
      - logo-login.svg
  - name: logo-header-configmap
    files:
      - logo-header.svg
  - name: favicon-configmap
    files:
      - favicon.ico

resources:
  - pv.yaml
  - pvc.yaml
  - awx.yaml
